package r01f.guids;

/**
 * Marker interface for {@link OID}s that are generated at DB level (ie ORACLE sequences)
 * and should NOT be generated by R01
 */
public interface OIDIsGenerated {
	// just a marker interface
}
